# Generated by Django 4.2.18 on 2025-04-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_report_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='submitted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
