# Generated by Django 5.1.6 on 2025-05-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analyzer', '0002_companyprofile_financialstatement_insidertransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_type', models.CharField(choices=[('interest_rate', 'Federal Funds Rate'), ('unemployment', 'Unemployment Rate'), ('inflation', 'Consumer Price Index'), ('gdp', 'GDP Growth Rate'), ('yield_curve', '10Y-2Y Treasury Spread')], max_length=50)),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('indicator_type', 'date')},
            },
        ),
    ]
